extends: ["spectral:oas"]
"overrides": [
  {
    "files": ["openapi.yaml"],
    "rules": {
      "operation-description": "off"
    }
  }
]
rules:
  x-domainInfo:
    description: Info object must have "x-domainInfo"
    given: $.info
    severity: error
    then:
      - field: x-domainInfo
        function: truthy